-- ============================================
-- SpirePanel 初始数据库表结构
-- Lite 版基础表 + Pro 版预留表结构
-- ============================================

-- 0. 扩展
create extension if not exists "pgcrypto" with schema "extensions";

-- 1. 租户表
create table if not exists public.tenants (
  id          uuid        primary key default gen_random_uuid(),
  name        text        not null,
  slug        text        not null unique,
  logo_url    text,
  contact_email text,
  contact_name  text,
  status      text        not null default 'active'
                          check (status in ('active', 'inactive')),
  plan_type   text        not null default 'lite'
                          check (plan_type in ('lite', 'pro')),
  max_users   integer     not null default 20,
  settings    jsonb       default '{}'::jsonb,
  metadata    jsonb       default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 2. 用户表（扩展 Supabase Auth）
create table if not exists public.users (
  id            uuid        primary key default gen_random_uuid(),
  email         text        not null unique,
  name          text,
  avatar_url    text,
  phone         text,
  is_super_admin boolean   not null default false,
  locale        text        not null default 'zh-CN',
  status        text        not null default 'active'
                            check (status in ('active', 'inactive', 'suspended')),
  last_login_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 3. 租户用户关联表
create table if not exists public.tenant_users (
  id        uuid        primary key default gen_random_uuid(),
  tenant_id uuid        not null references public.tenants(id) on delete cascade,
  user_id   uuid        not null references public.users(id) on delete cascade,
  role      text        not null default 'member'
                        check (role in ('owner', 'admin', 'member')),
  status    text        not null default 'active'
                        check (status in ('active', 'inactive')),
  joined_at timestamptz not null default now(),
  unique (tenant_id, user_id)
);

-- 4. 套餐表
create table if not exists public.plans (
  id            uuid        primary key default gen_random_uuid(),
  name          text        not null,
  code          text        not null unique,
  description   text,
  price_monthly numeric(10,2) not null default 0,
  price_yearly  numeric(10,2) not null default 0,
  features      jsonb       default '[]'::jsonb,
  sort_order    integer     not null default 0,
  is_active     boolean     not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 5. 订阅表
create table if not exists public.subscriptions (
  id            uuid        primary key default gen_random_uuid(),
  tenant_id     uuid        not null references public.tenants(id) on delete cascade,
  plan_id       uuid        not null references public.plans(id) on delete restrict,
  status        text        not null default 'active'
                            check (status in ('active', 'canceled', 'expired', 'trial')),
  billing_cycle text        not null default 'monthly'
                            check (billing_cycle in ('monthly', 'yearly')),
  start_at      timestamptz not null default now(),
  end_at        timestamptz,
  trial_end_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 6. 订单表
create table if not exists public.orders (
  id              uuid        primary key default gen_random_uuid(),
  tenant_id       uuid        not null references public.tenants(id) on delete cascade,
  order_no        text        not null unique,
  type            text        not null default 'subscription'
                              check (type in ('subscription', 'upgrade', 'renewal', 'one_time')),
  status          text        not null default 'pending'
                              check (status in ('pending', 'paid', 'failed', 'refunded', 'expired')),
  amount          numeric(10,2) not null,
  currency        text        not null default 'cny',
  payment_method  text,
  payment_channel text,
  payment_id      text,
  paid_at         timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- 7. 审计日志表
create table if not exists public.audit_logs (
  id            bigint      generated by default as identity primary key,
  tenant_id     uuid        references public.tenants(id) on delete set null,
  user_id       uuid        references public.users(id) on delete set null,
  action        text        not null,
  resource_type text        not null,
  resource_id   text,
  details       jsonb       default '{}'::jsonb,
  ip_address    inet,
  created_at    timestamptz not null default now()
);

-- 8. 触发器：自动更新 updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
declare
  t text;
begin
  for t in select unnest(array['tenants', 'users', 'plans', 'subscriptions', 'orders']) loop
    execute format(
      'create trigger if not exists %I before update on public.%I for each row execute function public.set_updated_at()',
      t || '_updated_at', t
    );
  end loop;
end;
$$;

-- 9. 触发器：新用户注册后自动创建 users 记录
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data ->> 'name')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- 10. RLS 启用
alter table public.tenants        enable row level security;
alter table public.users          enable row level security;
alter table public.tenant_users   enable row level security;
alter table public.plans          enable row level security;
alter table public.subscriptions  enable row level security;
alter table public.orders         enable row level security;
alter table public.audit_logs     enable row level security;

-- 11. RLS 策略：租户隔离
-- 用户只能看到自己所属租户的数据
create or replace function public.get_user_tenant_ids()
returns uuid[]
language sql stable
as $$
  select array_agg(tenant_id)
  from public.tenant_users
  where user_id = auth.uid()
    and status = 'active';
$$;

-- tenants: 只有超级管理员可查看所有，普通用户只能查看自己的
create policy "Users can view their own tenants"
  on public.tenants for select
  using (
    auth.role() = 'service_role'
    or id = any (public.get_user_tenant_ids())
  );

create policy "Super admins can manage tenants"
  on public.tenants for all
  using (auth.role() = 'service_role');

-- orders: 租户隔离
create policy "Users can view their tenant orders"
  on public.orders for select
  using (
    tenant_id = any (public.get_user_tenant_ids())
  );

create policy "Users can insert orders for their tenant"
  on public.orders for insert
  with check (
    tenant_id = any (public.get_user_tenant_ids())
  );

-- audit_logs: 租户隔离
create policy "Users can view their tenant audit logs"
  on public.audit_logs for select
  using (
    tenant_id = any (public.get_user_tenant_ids())
  );

-- 12. 索引
create index if not exists idx_tenant_users_user_id on public.tenant_users(user_id);
create index if not exists idx_tenant_users_tenant_id on public.tenant_users(tenant_id);
create index if not exists idx_orders_tenant_id on public.orders(tenant_id);
create index if not exists idx_orders_order_no on public.orders(order_no);
create index if not exists idx_subscriptions_tenant_id on public.subscriptions(tenant_id);
create index if not exists idx_audit_logs_tenant_id on public.audit_logs(tenant_id);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
